---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: recipes

resources:
  - namespace.yaml
  - externalsecret.yaml
  - externalsecret-openai.yaml
  - storage.yaml
  - mealie.yaml
  - bar-assistant.yaml
  - ingress-routes.yaml
  - certificate.yaml
  - networkpolicy.yaml
  - vpa.yaml
  - hpa.yaml
