---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-agent-token
  namespace: gitlab-agent
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-homelab
  target:
    name: gitlab-agent-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: GitLab Agent Token
        property: credential
