---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - exportarr/sonarr
  - exportarr/radarr
  - exportarr/lidarr
  - exportarr/prowlarr
  - blackbox-exporter.yaml
  - proxmox-exporter.yaml
  - zfs-exporter.yaml
  - adguard-exporter.yaml
  - unbound-exporter.yaml
  - node-exporter-host.yaml
  - plex-exporter.yaml
  - redis-exporter.yaml
  - dcgm-exporter.yaml
