---
# Plex role handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Reload systemd
  when: not (skip_plex_service | default(false))

- name: Restart plex
  ansible.builtin.systemd:
    name: plexmediaserver
    state: restarted
  when:
    - not ansible_check_mode
    - not (skip_plex_service | default(false))
  listen: Restart plex
