#!/usr/bin/env python3
"""Generate kubernetes/infrastructure/configs/versions-configmap.yaml from all.yml.

Reads version-related keys from ansible/inventories/prod/group_vars/all.yml and
emits a ConfigMap consumed by Flux Kustomizations via postBuild.substituteFrom.

Keys are flattened:
  - Top-level keys ending in _version pass through (e.g., authentik_version)
  - Nested keys under helm_chart_versions.* become helm_chart_versions_<name>
    (e.g., helm_chart_versions.traefik -> helm_chart_versions_traefik)

Idempotent. Run via `task flux:sync-versions`. CI fails if the committed output
differs from what this script produces.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml (or brew install python && pip3 install pyyaml)")

REPO = Path(__file__).resolve().parent.parent
ALL_YML = REPO / "ansible" / "inventories" / "prod" / "group_vars" / "all.yml"
OUT = REPO / "kubernetes" / "infrastructure" / "configs" / "versions-configmap.yaml"

VERSION_SUFFIX = "_version"
NESTED_KEYS = ("helm_chart_versions",)


def flatten(data: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    for k, v in data.items():
        if isinstance(v, (str, int, float)) and k.endswith(VERSION_SUFFIX):
            out[k] = str(v)
        elif k in NESTED_KEYS and isinstance(v, dict):
            for sub_k, sub_v in v.items():
                out[f"{k}_{sub_k}"] = str(sub_v)
    return out


def main() -> int:
    if not ALL_YML.exists():
        print(f"ERROR: {ALL_YML} not found", file=sys.stderr)
        return 1
    with ALL_YML.open() as f:
        data = yaml.safe_load(f)
    flat = flatten(data)
    if not flat:
        print("ERROR: no version keys extracted; check all.yml structure", file=sys.stderr)
        return 1
    cm = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {"name": "cluster-versions", "namespace": "flux-system"},
        "data": flat,
    }
    header = (
        "---\n"
        "# AUTO-GENERATED by scripts/generate-versions-configmap.py from\n"
        "# ansible/inventories/prod/group_vars/all.yml. Do NOT edit by hand.\n"
        "# Run `task flux:sync-versions` to regenerate. CI fails if out of sync.\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + yaml.safe_dump(cm, default_flow_style=False, sort_keys=True))
    print(f"Wrote {len(flat)} keys to {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
