#!/usr/bin/env python3
"""Generate the HostLogShippingStale rules from the Ansible inventory.

One rule per `alloy_host` host. `--check` exits 1 on drift. `--count` prints the rule count the inventory derives, not what the committed file carries;
LokiRulerRulesMissing thresholds on every loki/ rule file (sum in test_host_log_staleness.py).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - environment guard
    print("ERROR: PyYAML required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(2) from None

sys.path.insert(0, str(Path(__file__).resolve().parent))
try:
    import inventory_tree  # noqa: E402
except ImportError as exc:  # pragma: no cover - environment guard
    print(
        f"ERROR: {exc.name or 'inventory_tree'}.py must sit next to this script "
        "- re-vendor it from weisssrv-lib.",
        file=sys.stderr,
    )
    raise SystemExit(2) from None

REPO = Path(__file__).resolve().parent.parent
SITE_YML = "ansible/playbooks/site.yml"
HOSTS_YML = "ansible/inventories/prod/hosts.yml"
OUTPUT = "kubernetes/infrastructure/observability/loki/host-log-staleness.yaml"
ROLE = "alloy_host"
RUNBOOK = "12-runbooks.md"

HEADER = """\
# GENERATED by scripts/generate-host-log-staleness.py from the alloy_host play in
# ansible/playbooks/site.yml; run `task flux:sync-host-log-staleness` after an
# inventory change. Loki's ruler evaluates these; LokiRulerRulesMissing watches them.
groups:
  - name: host-log-staleness
    interval: 1m
    rules:
"""

DESCRIPTION = (
    "No journald line has reached Loki from {{ $labels.host }} in 45m. Its "
    "host-side Alloy is dead, the host is down, or the Loki push path is broken "
    "past the on-disk WAL. Check `systemctl status alloy` on {{ $labels.host }}, "
    "then the loki.${cluster_internal_domain} IngressRoute and the Loki pod."
)


class Vacuous(Exception):
    """The generator could not read its source — exit 2, never an empty file."""


def _role_names(play: dict) -> list[str]:
    """Short role names in a play's `roles:` list; roles ship FQCN'd."""
    names = []
    for entry in play.get("roles") or []:
        role = entry.get("role") if isinstance(entry, dict) else entry
        if isinstance(role, str) and role:
            names.append(role.rsplit(".", 1)[-1])
    return names


def target_groups(site_yml: Path) -> tuple[list[str], list[str]]:
    """The play's included and `!`-excluded group tokens, in written order.

    An excluded host never runs the role, so it ships no journald and gets no
    rule; alerting on it would fire forever.
    """
    try:
        # The handle, not the text: PyYAML names the file in its error mark.
        with site_yml.open(encoding="utf-8") as handle:
            plays = yaml.safe_load(handle)
    except (OSError, UnicodeDecodeError, yaml.YAMLError) as exc:
        raise Vacuous(f"{SITE_YML} unreadable: {exc}") from exc
    matches = [p for p in (plays or []) if isinstance(p, dict) and ROLE in _role_names(p)]
    if len(matches) != 1:
        raise Vacuous(f"{SITE_YML}: expected exactly one {ROLE} play, found {len(matches)}")
    expression = matches[0]["hosts"]
    parts = expression if isinstance(expression, list) else [expression]
    tokens = [t for part in parts for t in str(part).split(":") if t]
    return (
        [t for t in tokens if not t.startswith("!")],
        [t.lstrip("!") for t in tokens if t.startswith("!")],
    )


def alloy_hosts(root: Path) -> list[str]:
    """The alloy_host host set, in the order site.yml + hosts.yml produce it."""
    try:
        index = inventory_tree.group_index(inventory_tree.load_inventory(root / HOSTS_YML))
        groups, excludes = target_groups(root / SITE_YML)
    except (OSError, UnicodeDecodeError, yaml.YAMLError) as exc:
        raise Vacuous(f"inventory unreadable: {exc}") from exc
    ordered: list[str] = []
    for group in groups:
        # An empty group is normal: a fresh cluster declares a group before it
        # has any hosts. Only the whole play resolving to nothing is a fault.
        if group not in index:
            raise Vacuous(f"the play targets group {group!r}, which the inventory does not declare")
        for host in inventory_tree.resolve_hosts(group, index, strict=True):
            if host not in ordered:
                ordered.append(host)
    # An undeclared exclusion is not an error; Ansible tolerates one too.
    excluded = {
        host for group in excludes for host in inventory_tree.resolve_hosts(group, index, strict=True)
    }
    ordered = [host for host in ordered if host not in excluded]
    if not ordered:
        raise Vacuous("the alloy_host play resolved to no hosts")
    return ordered


def render(hosts: list[str]) -> str:
    body = [HEADER]
    for host in hosts:
        body.append(
            f'      - alert: HostLogShippingStale\n'
            f'        expr: absent_over_time({{job="journal", host="{host}"}}[45m])\n'
            f'        for: 15m\n'
            f"        labels: {{ severity: warning, component: logging, "
            f"host: {host}, instance: {host} }}\n"
            f"        annotations:\n"
            f'          summary: "No journald logs from {{{{ $labels.host }}}} in 45m '
            f'(alloy_host shipping stopped)"\n'
            f'          description: "{DESCRIPTION}"\n'
            f'          runbook_url: "${{cluster_runbook_base_url}}/{RUNBOOK}"\n'
        )
    return "".join(body)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate the HostLogShippingStale rules")
    parser.add_argument("--repo-root", default=str(REPO))
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    parser.add_argument(
        "--count",
        action="store_true",
        help="print the alloy_host rule count the inventory derives (not the "
             "LokiRulerRulesMissing threshold, and not what the committed file carries)",
    )
    args = parser.parse_args(argv)
    root = Path(args.repo_root)

    try:
        hosts = alloy_hosts(root)
    except Vacuous as exc:
        print(f"generate-host-log-staleness: {exc}", file=sys.stderr)
        return 2

    if args.count:
        print(len(hosts))
        return 0

    wanted = render(hosts)
    target = root / OUTPUT
    current = target.read_text() if target.exists() else ""
    if args.check:
        # The generator owns the whole file, header included, so a hand-edited
        # header is drift too.
        if current != wanted:
            print(
                f"{OUTPUT} is stale ({len(hosts)} alloy_host hosts in the inventory) — "
                "run `task flux:sync-host-log-staleness`",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT} is in step with the inventory ({len(hosts)} hosts).")
        return 0
    target.write_text(wanted)
    print(f"Wrote {OUTPUT} ({len(hosts)} hosts).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
