#!/usr/bin/env python3
"""Generate scripts/hosts.env from ansible/inventories/prod/hosts.yml.

hosts.yml is the single source of truth for the cluster's host/IP roster. This
script flattens the groups an operator tool actually needs into a small,
shell-sourceable (and go-task `dotenv:`-loadable) env file so the roster is
defined once instead of being hand-copied into the Taskfile, collect-state.sh,
diagnose-network-issues.sh, and the CI ssh-keyscan list.

Consumers:
  - Taskfile.yml           via `dotenv: ['scripts/hosts.env']` — {{.PVE_HOSTS}}
                           (hostnames) and {{.K3S_SERVERS}} (IPs).
  - scripts/collect-state.sh          `. hosts.env` — builds its host arrays.
  - scripts/diagnose-network-issues.sh `. hosts.env` — PVE_IPS + K3S_SERVERS.
  - .gitlab-ci.yml (.deploy-base)      $ALL_SSH_IPS for the TOFU keyscan.
  - kubernetes NetworkPolicies (out of this repo's tooling scope) reuse the
    K3S_SERVERS values as the apiserver egress allowlist — kept in step here.

Precedent: scripts/generate-versions-configmap.py + the flux-versions-sync CI
drift job. This script is idempotent; the hosts-env-sync CI job fails if the
committed output differs from what this produces. Run via `task hosts:sync`.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
HOSTS_YML = REPO / "ansible" / "inventories" / "prod" / "hosts.yml"
OUT = REPO / "scripts" / "hosts.env"


def _group_hosts(data: dict, group: str) -> dict:
    """Return the {name: hostvars} mapping for a top-level inventory group."""
    children = (data.get("all") or {}).get("children") or {}
    return (children.get(group) or {}).get("hosts") or {}


def _ips(data: dict, group: str) -> list[str]:
    hosts = _group_hosts(data, group)
    out: list[str] = []
    for name, hv in hosts.items():
        ip = (hv or {}).get("ansible_host")
        if not ip:
            raise ValueError(f"host {name!r} in group {group!r} has no ansible_host")
        out.append(str(ip))
    return out


def _required_ips(data: dict, group: str) -> list[str]:
    """Like _ips, but fail loudly when a required group resolves to zero hosts
    (renamed/removed in hosts.yml) instead of emitting an empty roster value."""
    ips = _ips(data, group)
    if not ips:
        raise ValueError(
            f"required group {group!r} resolved to zero hosts — renamed/removed in hosts.yml?"
        )
    return ips


def build(data: dict) -> list[tuple[str, str]]:
    """Return ordered (KEY, space-joined-value) pairs for hosts.env."""
    pve = _group_hosts(data, "proxmox")
    pve_names = list(pve.keys())
    pve_ips = _required_ips(data, "proxmox")

    dns_ips = _required_ips(data, "dns")
    mail_ips = _required_ips(data, "mail")
    plex_ips = _required_ips(data, "plex_servers")
    gitlab_ips = _required_ips(data, "gitlab_servers")
    nextcloud_ips = _required_ips(data, "nextcloud_servers")
    immich_ips = _required_ips(data, "immich_servers")

    services = _group_hosts(data, "services")
    home_ip = str((services.get("home") or {}).get("ansible_host") or "")
    windows_ip = str((services.get("windows") or {}).get("ansible_host") or "")
    if not home_ip:
        raise ValueError("services.home has no ansible_host")

    k3s_servers = _required_ips(data, "k3s_servers")
    k3s_agents = _required_ips(data, "k3s_agents")

    # ssh-keyscan / general SSH reachability set: every host CI or an operator
    # SSHes into. Excludes the Windows guest (.155) — it runs no sshd we manage,
    # matching the pre-generator keyscan list.
    all_ssh = (
        pve_ips
        + dns_ips
        + mail_ips
        + plex_ips
        + gitlab_ips
        + nextcloud_ips
        + immich_ips
        + [home_ip]
        + k3s_servers
        + k3s_agents
    )

    pairs: list[tuple[str, str]] = [
        ("PVE_HOSTS", " ".join(pve_names)),
        ("PVE_IPS", " ".join(pve_ips)),
        ("DNS_IPS", " ".join(dns_ips)),
        ("MAIL_IPS", " ".join(mail_ips)),
        ("PLEX_IP", " ".join(plex_ips)),
        ("GITLAB_IP", " ".join(gitlab_ips)),
        ("NEXTCLOUD_IP", " ".join(nextcloud_ips)),
        ("IMMICH_IP", " ".join(immich_ips)),
        ("HOME_ASSISTANT_IP", home_ip),
        ("WINDOWS_IP", windows_ip),
        ("K3S_SERVERS", " ".join(k3s_servers)),
        ("K3S_AGENTS", " ".join(k3s_agents)),
        ("ALL_SSH_IPS", " ".join(all_ssh)),
    ]
    return pairs


HEADER = (
    "# AUTO-GENERATED by scripts/generate-hosts-env.py from\n"
    "# ansible/inventories/prod/hosts.yml. Do NOT edit by hand.\n"
    "# Run `task hosts:sync` to regenerate. CI fails if out of sync.\n"
    "#\n"
    "# Shell-sourceable and go-task `dotenv:`-loadable. PVE_HOSTS is hostnames\n"
    "# (Tailscale/LAN resolvable); every other list is IPs.\n"
)


def render(pairs: list[tuple[str, str]]) -> str:
    lines = [HEADER]
    for key, value in pairs:
        lines.append(f'{key}="{value}"\n')
    return "".join(lines)


def main() -> int:
    if not HOSTS_YML.exists():
        print(f"ERROR: {HOSTS_YML} not found", file=sys.stderr)
        return 1
    try:
        with HOSTS_YML.open() as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError as e:
        print(f"ERROR: failed to parse {HOSTS_YML.relative_to(REPO)}: {e}", file=sys.stderr)
        return 1
    if not isinstance(data, dict):
        print(f"ERROR: {HOSTS_YML.relative_to(REPO)} top-level is not a mapping", file=sys.stderr)
        return 1
    try:
        pairs = build(data)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    try:
        OUT.write_text(render(pairs))
    except OSError as e:
        print(f"ERROR: failed to write {OUT}: {e}", file=sys.stderr)
        return 1
    print(f"Wrote {len(pairs)} keys to {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
