---
apiVersion: v1
kind: Service
metadata:
  name: exportarr-arr
  namespace: observability
  labels:
    app.kubernetes.io/name: exportarr-arr
spec:
  selector:
    app.kubernetes.io/name: exportarr-arr
  ports:
    - name: metrics
      port: 9707
